language: python
python:
    - 2.6
    - 2.7
install:
  - pip install setuptools -U
  - python bootstrap.py
  - bin/buildout -c travis.cfg
branches:
  only:
    - master
script:
  - bin/code-analysis
  - bin/test
notifications:
  irc: irc.freenode.org#propertyshelf
