language: python
python:
    - 2.6
    - 2.7
sudo: false
cache:
  directories:
    - eggs
install:
  - sed -ie "s#versions-$TRAVIS_PYTHON_VERSION.x#versions#" travis.cfg
  - pip install -r requirements.txt
  - buildout -c travis.cfg annotate
  - buildout -c travis.cfg -N -q
branches:
  only:
    - master
script:
  - bin/code-analysis
  - bin/test
notifications:
  hipchat:
    secure: "bbubw9kTTCbr7Lk5+GeeinNt6BpeCPrJ/cSDYJYfYuQcB28n+NbzOvxcGNVyfTJtsxqRD41ZaqINS14xmurHzpg+h6GINIUY56WIQVXZSwO8dvR1IsRDPEy3oVqyHkVpQ18TqeA4k0tUno6spaI3pHT12iKvu2T/uhgphPD07qY="
